services:
  - type: web
    name: ai-job-matching-backend
    runtime: docker
    rootDir: ai-job-matching
    dockerfilePath: ./Dockerfile
    plan: free
    autoDeploy: true
    healthCheckPath: /job/all
    envVars:
      - key: SERVER_PORT
        value: "8080"
      - key: JPA_DDL_AUTO
        value: update
      - key: JPA_SHOW_SQL
        value: false
      - key: JOBS_IMPORT_SCHEDULER_ENABLED
        value: false
      - key: MAIL_ENABLED
        value: true
      - key: MAIL_PROVIDER
        value: gmail-api
      - key: DB_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: MAIL_FROM
        sync: false
      - key: GMAIL_CLIENT_ID
        sync: false
      - key: GMAIL_CLIENT_SECRET
        sync: false
      - key: GMAIL_REFRESH_TOKEN
        sync: false
      - key: GMAIL_TOKEN_URL
        value: https://oauth2.googleapis.com/token
      - key: GMAIL_SEND_URL
        value: https://gmail.googleapis.com/gmail/v1/users/me/messages/send
      - key: MAIL_CONNECTION_TIMEOUT_MS
        value: "5000"
      - key: MAIL_READ_TIMEOUT_MS
        value: "10000"
      - key: ADZUNA_APP_ID
        sync: false
      - key: ADZUNA_APP_KEY
        sync: false
      - key: HF_TOKEN
        sync: false

  - type: static_site
    name: ai-job-matching-ui
    rootDir: ai-job-matching-ui
    buildCommand: npm install && npm run build
    publishPath: dist
    pullRequestPreviewsEnabled: true
