spring.datasource.url=jdbc:postgresql://dpg-d6mn5s6a2pns73d9thmg-a:5432/ai_job_matcher
spring.datasource.username=ai_user
spring.datasource.password=ORxQVnoczp5Ynplg5FldRaI4uiNVNxp9
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=5
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=anujdutta44@gmail.com
spring.mail.password=YOUR_APP_PASSWORD
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

adzuna.app_id=36c88380
adzuna.app_key=e7f9f6960e24494b2f979bdd4f27fae