spring.datasource.url=jdbc:mysql://localhost:3306/resume_ai
spring.datasource.username=root
spring.datasource.password=anuj

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true

server.port=8080

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=anujdutta44@gmail.com
spring.mail.password=nndyoduhrjyghfhw
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.debug=true

adzuna.app.id=36c883a0
adzuna.app.key=e7f7fe6902e449b4b2f979bdd4f27fae